- hosts: localhost
  tasks:
  - name: Create user
    command: useradd -m "{{ '{{student_name}}' }}"

  - include_role:
      name: "{{ '{{item}}' }}"
    with_items:
      - "{{ '{{infra_workloads}}' }}"